'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SynapseMemory}=require('../src/synapseMemory');const {OpenAIModelProvider,LocalModelProvider,AutoModelRouter,CompactConversationState}=require('../src/modelProviders');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rh-memory-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new SynapseMemory(path.join(dir,'memory.json'));}
test('explicit Golden Cage and taste memory survive new store/router sessions',async t=>{const m=temp(t);m.command('Remember this: My Golden Cage has been the #1 standby result about six refreshes in a row. Do not keep placing it at the top. Apply a cooldown and prioritize genuinely fresh tracks.');m.command('Remember this: I prefer long progressive house with minimal vocals.');const fresh=new SynapseMemory(m.file);assert.match(fresh.context('standby refresh novelty'),/Golden Cage/);assert.match(fresh.context('What kind of progressive house do I prefer?'),/minimal vocals/);const router=new AutoModelRouter({memory:fresh});const response=await router.respond({message:'Show what Synapse remembers about my music taste.'});assert.match(response.text,/progressive house/);});
test('relevance, priority, expiry, sensitivity and bounded context',t=>{const m=temp(t);m.upsert({text:'My truck requires diesel.',category:'user_preferences'});m.upsert({text:'Ableton project uses a private synthesizer.',category:'project_state'});m.upsert({text:'Do not repeat Golden Cage in standby.',category:'user_rules',source:'explicit_user'});m.upsert({text:'Progressive house private preference.',sensitive:true});m.upsert({text:'Progressive house expired.',expiresAt:'2020-01-01'});for(let i=0;i<30;i++)m.upsert({text:`Progressive house taste ${i}. `+'x'.repeat(300)});const selected=m.retrieve('standby progressive house');assert.equal(selected[0].category,'user_rules');const context=m.context('standby progressive house');assert.ok(!/truck|Ableton|private preference|expired/.test(context));assert.ok(selected.length<=12);assert.ok(context.length<5200);assert.match(context,/current explicit user instruction > saved explicit rules/);});
test('imports, edit, forget and credential rejection',t=>{const m=temp(t);m.import('# Music preferences\n- Prefer progressive house\n- Minimal vocals');assert.equal(m.read().entries.length,2);const first=m.read().entries[0];m.command(`Update this preference: ${first.id} | Prefer melodic progressive house`);assert.equal(m.read().entries.length,2);assert.match(m.read().entries.find(e=>e.id===first.id).text,/melodic/);assert.throws(()=>m.import('password: supersecret'),/Credentials/);assert.throws(()=>m.upsert({text:'Token sk-abcdefghijklmnop123456'}),/Credentials/);m.command('Forget this: '+first.id);assert.equal(m.read().entries.length,1);const copy=temp(t);copy.import(JSON.stringify(m.read()));assert.equal(copy.read().entries.length,1);});
test('conversation storage and deterministic rolling summary stay bounded and omit credentials',t=>{const m=temp(t);const c=new CompactConversationState(8,m);for(let i=0;i<60;i++)c.add(i%2?'assistant':'user','Music conversation '+i+' '+ 'x'.repeat(1000));c.add('user','api_key: private-secret');const db=m.read();assert.equal(db.recentTurns.length,12);assert.ok(db.rollingSummary.length<=1800);assert.ok(!JSON.stringify(db).includes('private-secret'));assert.equal(db.entries.filter(e=>e.id==='rolling-conversation').length,1);const fresh=new CompactConversationState(8,new SynapseMemory(m.file));assert.equal(fresh.turns.length,8);});
test('OpenAI injects shared memory on initial and follow-up requests, with stable identity',async t=>{const m=temp(t);m.upsert({text:'Do not repeat Golden Cage in standby.',category:'user_rules'});const requests=[];const provider=new OpenAIModelProvider({memory:m,config:{enabled:true,apiKey:'test',model:'test-model'},fetch:async(url,opt)=>{requests.push(JSON.parse(opt.body));return {ok:true,status:200,text:async()=>JSON.stringify({output:[]})};}});await provider.postResponse({model:'test',input:'standby refresh'});await provider.postResponse({model:'test',previous_response_id:'response',input:[{type:'function_call_output',output:'ok'}]},{memoryQuery:'standby refresh'});assert.ok(requests.every(r=>r.instructions.includes('Golden Cage')&&r.instructions.includes('You are Synapse')));});
test('Qwen reads the same memory store',async t=>{const m=temp(t);m.upsert({text:'Prefer long progressive house.'});let sent;const provider=new LocalModelProvider({memory:m,config:{llmProvider:'ollama',ollamaBaseUrl:'http://local',ollamaModel:'qwen'},fetch:async(url,opt)=>{sent=JSON.parse(opt.body);return {ok:true,text:async()=>JSON.stringify({message:{content:'ok'}})};}});await provider.chatModel('progressive house preferences');assert.match(JSON.stringify(sent),/Prefer long progressive house/);});

test('older explicit preference statements become durable facts without model inference',t=>{const m=temp(t);m.recordTurn('user','I prefer progressive house with long evolving arrangements.');for(let i=0;i<20;i++)m.recordTurn('assistant','Routine response '+i);const fresh=new SynapseMemory(m.file);assert.ok(fresh.read().entries.some(e=>e.source==='conversation_user_statement'&&e.text.includes('long evolving')));});
